language: node_js
after_success:
  - zip table-soccer-legends.zip index.html bg.jpg main.js
  - "curl -F 'data=@table-soccer-legends.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: nielsgerritsen/table-soccer-legends' https://carehr.nl/deploy/"
